# Generated by codegen.py
# Do not edit this file directly.
from __future__ import annotations

from typing import Callable, Literal, LiteralString, Self, override, overload
from tree_sitter import Node, Point, Language, Parser, Tree, TreeCursor, Range
from collections.abc import ByteString

class HclLanguage(Language):  # pyright: ignore[reportGeneralTypeIssues]
    pass

class HclParser(Parser):  # pyright: ignore[reportGeneralTypeIssues]
    @property
    @override
    def language(self) -> HclLanguage | None: ...
    @language.setter
    @override
    def language(self, language: HclLanguage) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @override
    @overload
    def parse(
        self,
        source: ByteString,
        /,
        old_tree: HclTree | None = None,
        encoding: Literal["utf8", "utf16", "utf16le", "utf16be"] = "utf8",
    ) -> HclTree: ...
    @overload
    def parse(  # pyright: ignore[reportIncompatibleMethodOverride]
        self,
        read_callback: Callable[[int, Point], bytes | None],
        /,
        old_tree: HclTree | None = None,
        encoding: Literal["utf8", "utf16", "utf16le", "utf16be"] = "utf8",
        progress_callback: Callable[[int, bool], bool] | None = None,
    ) -> HclTree: ...

class HclTree(Tree):  # pyright: ignore[reportGeneralTypeIssues]
    @property
    @override
    def root_node(self) -> HclNode: ...

    @property
    @override
    def language(self) -> HclLanguage: ...

    def root_node_with_offset(
        self,
        offset_bytes: int,
        offset_extent: Point | tuple[int, int],
        /,
    ) -> HclNode | None: ...
    @override
    def copy(self) -> HclTree: ...
    @override
    def walk(self) -> HclTreeCursor: ...
    @override
    def changed_ranges(self, new_tree: HclTree, /) -> list[Range]: ... # pyright: ignore[reportIncompatibleMethodOverride]
    @override
    def __copy__(self) -> HclTree: ...

class HclTreeCursor(TreeCursor):  # pyright: ignore[reportGeneralTypeIssues]
    @property
    @override
    def node(self) -> HclNode | None: ...
    @override
    def copy(self) -> Self: ...
    @override
    def reset(self, node: HclNode, /) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @override
    def reset_to(self, cursor: Self, /) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @override
    def __copy__(self) -> Self: ...

class Base[T = LiteralString](Node):  # pyright: ignore[reportGeneralTypeIssues]
    @property
    @override
    def type(self) -> T: ... # pyright: ignore[reportIncompatibleMethodOverride]

    @property
    def children(self) -> list[HclNode]: ...
    @property
    def child_count(self) -> int: ...
    @property
    def named_children(self) -> list[HclNode]: ...
    @property
    def named_child_count(self) -> int: ...
    @property
    def parent(self) -> HclNode | None: ...
    @property
    def next_sibling(self) -> HclNode | None: ...
    @property
    def prev_sibling(self) -> HclNode | None: ...
    @property
    def next_named_sibling(self) -> HclNode | None: ...
    @property
    def prev_named_sibling(self) -> HclNode | None: ...
    @property
    def descendant_count(self) -> int: ...
    def child(self, index: int, /) -> HclNode | None: ...
    def named_child(self, index: int, /) -> HclNode | None: ...
    def first_child_for_byte(self, byte: int, /) -> HclNode | None: ...
    def first_named_child_for_byte(self, byte: int, /) -> HclNode | None: ...
    def child_by_field_id(self, id: int, /) -> HclNode | None: ...
    def child_by_field_name(self, name: str, /) -> HclNode | None: ...
    def child_with_descendant(self, descendant: HclNode, /) -> HclNode | None: ...
    def children_by_field_id(self, id: int, /) -> list[HclNode]: ...
    def children_by_field_name(self, name: str, /) -> list[HclNode]: ...
    def descendant_for_byte_range(
        self,
        start_byte: int,
        end_byte: int,
        /,
    ) -> HclNode | None: ...
    def named_descendant_for_byte_range(
        self,
        start_byte: int,
        end_byte: int,
        /,
    ) -> HclNode | None: ...
    def descendant_for_point_range(
        self,
        start_point: Point | tuple[int, int],
        end_point: Point | tuple[int, int],
        /,
    ) -> HclNode | None: ...
    def named_descendant_for_point_range(
        self,
        start_point: Point | tuple[int, int],
        end_point: Point | tuple[int, int],
        /,
    ) -> HclNode | None: ...
    # @override
    # def child_by_field_name(self, name: str, /) -> LanguageNode | None: ...
    # @override
    # def children_by_field_name(self, name: str, /) -> list[LanguageNode]: ... # pyright: ignore[reportIncompatibleMethodOverride]

class NamedNode[T](Base[T]):
    @property
    @override
    def is_named(self) -> Literal[True]: ...

class UnnamedNode[T](Base[T]):
    @property
    @override
    def is_named(self) -> Literal[False]: ...