# Generated by codegen.py
# Do not edit this file directly.
from __future__ import annotations

from typing import Callable, Literal, LiteralString, Self, override, overload
from tree_sitter import Node, Point, Language, Parser, Tree, TreeCursor, Range
from collections.abc import ByteString

class HclLanguage(Language):  # pyright: ignore[reportGeneralTypeIssues]
    pass

class HclParser(Parser):  # pyright: ignore[reportGeneralTypeIssues]
    @property
    @override
    def language(self) -> HclLanguage | None: ...
    @language.setter
    @override
    def language(self, language: HclLanguage) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @override
    @overload
    def parse(
        self,
        source: ByteString,
        /,
        old_tree: HclTree | None = None,
        encoding: Literal["utf8", "utf16", "utf16le", "utf16be"] = "utf8",
    ) -> HclTree: ...
    @overload
    def parse(  # pyright: ignore[reportIncompatibleMethodOverride]
        self,
        read_callback: Callable[[int, Point], bytes | None],
        /,
        old_tree: HclTree | None = None,
        encoding: Literal["utf8", "utf16", "utf16le", "utf16be"] = "utf8",
        progress_callback: Callable[[int, bool], bool] | None = None,
    ) -> HclTree: ...

class HclTree(Tree):  # pyright: ignore[reportGeneralTypeIssues]
    @property
    @override
    def root_node(self) -> HclNode: ...
    @property
    @override
    def language(self) -> HclLanguage: ...
    def root_node_with_offset(
        self,
        offset_bytes: int,
        offset_extent: Point | tuple[int, int],
        /,
    ) -> HclNode | None: ...
    @override
    def copy(self) -> HclTree: ...
    @override
    def walk(self) -> HclTreeCursor: ...
    @override
    def changed_ranges(self, new_tree: HclTree, /) -> list[Range]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @override
    def __copy__(self) -> HclTree: ...

class HclTreeCursor(TreeCursor):  # pyright: ignore[reportGeneralTypeIssues]
    @property
    @override
    def node(self) -> HclNode | None: ...
    @override
    def copy(self) -> Self: ...
    @override
    def reset(self, node: HclNode, /) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @override
    def reset_to(self, cursor: Self, /) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @override
    def __copy__(self) -> Self: ...

class Base[T = LiteralString](Node):  # pyright: ignore[reportGeneralTypeIssues]
    @property
    @override
    def type(self) -> T: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @property
    def children(self) -> list[HclNode]: ...
    @property
    def child_count(self) -> int: ...
    @property
    def named_children(self) -> list[HclNode]: ...
    @property
    def named_child_count(self) -> int: ...
    @property
    def parent(self) -> HclNode | None: ...
    @property
    def next_sibling(self) -> HclNode | None: ...
    @property
    def prev_sibling(self) -> HclNode | None: ...
    @property
    def next_named_sibling(self) -> HclNode | None: ...
    @property
    def prev_named_sibling(self) -> HclNode | None: ...
    @property
    def descendant_count(self) -> int: ...
    def child(self, index: int, /) -> HclNode | None: ...
    def named_child(self, index: int, /) -> HclNode | None: ...
    def first_child_for_byte(self, byte: int, /) -> HclNode | None: ...
    def first_named_child_for_byte(self, byte: int, /) -> HclNode | None: ...
    def child_by_field_id(self, id: int, /) -> HclNode | None: ...
    def child_by_field_name(self, name: str, /) -> HclNode | None: ...
    def child_with_descendant(self, descendant: HclNode, /) -> HclNode | None: ...
    def children_by_field_id(self, id: int, /) -> list[HclNode]: ...
    def children_by_field_name(self, name: str, /) -> list[HclNode]: ...
    def descendant_for_byte_range(
        self,
        start_byte: int,
        end_byte: int,
        /,
    ) -> HclNode | None: ...
    def named_descendant_for_byte_range(
        self,
        start_byte: int,
        end_byte: int,
        /,
    ) -> HclNode | None: ...
    def descendant_for_point_range(
        self,
        start_point: Point | tuple[int, int],
        end_point: Point | tuple[int, int],
        /,
    ) -> HclNode | None: ...
    def named_descendant_for_point_range(
        self,
        start_point: Point | tuple[int, int],
        end_point: Point | tuple[int, int],
        /,
    ) -> HclNode | None: ...
    # @override
    # def child_by_field_name(self, name: str, /) -> LanguageNode | None: ...
    # @override
    # def children_by_field_name(self, name: str, /) -> list[LanguageNode]: ... # pyright: ignore[reportIncompatibleMethodOverride]

class NamedNode[T](Base[T]):
    @property
    @override
    def is_named(self) -> Literal[True]: ...

class UnnamedNode[T](Base[T]):
    @property
    @override
    def is_named(self) -> Literal[False]: ...

type SyntaxType = Literal[
    "strip_marker",
    "template_else_intro",
    "template_literal",
    "template_directive_end",
    "block_start",
    "body",
    "index",
    "for_initializer_pair",
    "for_object_expr",
    "heredoc_template",
    "get_attr",
    "for_intro",
    "collection_value",
    "splat",
    "quoted_template",
    "attribute",
    "template_for",
    "binary_operation",
    "new_index",
    "object_end",
    "for_initializer_single",
    "null_lit",
    "template_if_end",
    "identifier",
    "quoted_template_start",
    "tuple",
    "expression",
    "template_directive_start",
    "template_expr",
    "comment",
    "conditional",
    "quoted_template_end",
    "legacy_index",
    "object",
    "object_start",
    "parenthesized_expression",
    "block_end",
    "bool_lit",
    "for_expr",
    "template_interpolation_start",
    "expr_term",
    "heredoc_identifier",
    "template_interpolation",
    "function_call",
    "unary_operation",
    "tuple_end",
    "template_if",
    "full_splat",
    "literal_value",
    "for_tuple_expr",
    "object_elem",
    "template_if_intro",
    "block",
    "template_interpolation_end",
    "attr_splat",
    "tuple_start",
    "ellipsis",
    "template_for_start",
    "heredoc_start",
    "config_file",
    "numeric_lit",
    "string_lit",
    "template_directive",
    "template_for_end",
]
type UnnamedType = Literal[
    "!=",
    "endif",
    ".*",
    "+",
    "-",
    "==",
    "[*]",
    "<<",
    "<<-",
    ")",
    "||",
    "]",
    "%",
    "/",
    "<",
    "for",
    "=",
    "(",
    "endfor",
    "}",
    "?",
    "{",
    ">=",
    ",",
    "[",
    "false",
    ":",
    "&&",
    ".",
    "=>",
    ">",
    "if",
    "in",
    "true",
    "*",
    "else",
    "!",
    "<=",
]

type TypeString = SyntaxType | UnnamedType

class AttrSplat(NamedNode[Literal["attr_splat"]]):
    ...
    @override
    def child_by_field_name(self, name: Literal["expression"], /) -> Expression: ...

class Attribute(NamedNode[Literal["attribute"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["left"], /) -> Identifier: ...
    @overload
    def child_by_field_name(self, name: Literal["right"], /) -> Expression: ...

class BinaryOperation(NamedNode[Literal["binary_operation"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["left"], /) -> ExprTerm: ...
    @overload
    def child_by_field_name(
        self, name: Literal["operator"], /
    ) -> (
        UnnamedNode[Literal["!="]]
        | UnnamedNode[Literal["%"]]
        | UnnamedNode[Literal["&&"]]
        | UnnamedNode[Literal["*"]]
        | UnnamedNode[Literal["+"]]
        | UnnamedNode[Literal["-"]]
        | UnnamedNode[Literal["/"]]
        | UnnamedNode[Literal["<"]]
        | UnnamedNode[Literal["<="]]
        | UnnamedNode[Literal["=="]]
        | UnnamedNode[Literal[">"]]
        | UnnamedNode[Literal[">="]]
        | UnnamedNode[Literal["||"]]
    ): ...
    @overload
    def child_by_field_name(self, name: Literal["right"], /) -> ExprTerm: ...

class Block(NamedNode[Literal["block"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["body"], /) -> Body | None: ...
    @override
    def children_by_field_name(
        self, name: Literal["labels"], /
    ) -> list[Identifier | StringLit]: ...
    @overload
    def child_by_field_name(self, name: Literal["type"], /) -> Identifier: ...
    @property
    @override
    def named_children(self) -> list[BlockEnd | BlockStart]: ...
    @property
    @override
    def children(self) -> list[BlockEnd | BlockStart]: ...

class BlockEnd(NamedNode[Literal["block_end"]]): ...
class BlockStart(NamedNode[Literal["block_start"]]): ...

class Body(NamedNode[Literal["body"]]):
    ...
    @override
    @overload
    def children_by_field_name(
        self, name: Literal["attributes"], /
    ) -> list[Attribute]: ...
    @overload
    def children_by_field_name(self, name: Literal["blocks"], /) -> list[Block]: ...

class BoolLit(NamedNode[Literal["bool_lit"]]): ...

class Conditional(NamedNode[Literal["conditional"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["alternative"], /) -> Expression: ...
    @overload
    def child_by_field_name(self, name: Literal["condition"], /) -> Expression: ...
    @overload
    def child_by_field_name(self, name: Literal["consequence"], /) -> Expression: ...

class ConfigFile(NamedNode[Literal["config_file"]]):
    ...

    @property
    @override
    def named_children(self) -> list[Body | Object]: ...
    @property
    @override
    def children(self) -> list[Body | Object]: ...

class ForInitializerPair(NamedNode[Literal["for_initializer_pair"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["left"], /) -> Identifier: ...
    @overload
    def child_by_field_name(self, name: Literal["right"], /) -> Identifier: ...

class ForIntro(NamedNode[Literal["for_intro"]]):
    ...
    @override
    @overload
    def child_by_field_name(
        self, name: Literal["left"], /
    ) -> ForInitializerPair | ForInitializerSingle: ...
    @overload
    def child_by_field_name(self, name: Literal["right"], /) -> Expression: ...

class ForObjectExpr(NamedNode[Literal["for_object_expr"]]):
    ...
    @override
    @overload
    def child_by_field_name(
        self, name: Literal["condition"], /
    ) -> Expression | None: ...
    @overload
    def child_by_field_name(self, name: Literal["expansion"], /) -> Ellipsis | None: ...
    @overload
    def child_by_field_name(self, name: Literal["intro"], /) -> ForIntro: ...
    @overload
    def child_by_field_name(self, name: Literal["key"], /) -> Expression: ...
    @overload
    def child_by_field_name(self, name: Literal["value"], /) -> Expression: ...
    @property
    @override
    def named_children(self) -> list[ObjectEnd | ObjectStart]: ...
    @property
    @override
    def children(self) -> list[ObjectEnd | ObjectStart]: ...

class ForTupleExpr(NamedNode[Literal["for_tuple_expr"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["body"], /) -> Expression: ...
    @overload
    def child_by_field_name(
        self, name: Literal["condition"], /
    ) -> Expression | None: ...
    @overload
    def child_by_field_name(self, name: Literal["intro"], /) -> ForIntro: ...
    @property
    @override
    def named_children(self) -> list[TupleEnd | TupleStart]: ...
    @property
    @override
    def children(self) -> list[TupleEnd | TupleStart]: ...

class FullSplat(NamedNode[Literal["full_splat"]]):
    ...
    @override
    def child_by_field_name(self, name: Literal["expression"], /) -> Expression: ...

class FunctionCall(NamedNode[Literal["function_call"]]):
    ...
    @override
    def children_by_field_name(
        self, name: Literal["arguments"], /
    ) -> list[Expression]: ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["expansion"], /) -> Ellipsis | None: ...
    @overload
    def child_by_field_name(self, name: Literal["function"], /) -> Identifier: ...

class GetAttr(NamedNode[Literal["get_attr"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["attribute"], /) -> Identifier: ...
    @overload
    def child_by_field_name(self, name: Literal["object"], /) -> ExprTerm: ...

class HeredocStart(NamedNode[Literal["heredoc_start"]]): ...

class HeredocTemplate(NamedNode[Literal["heredoc_template"]]):
    ...
    @override
    def children_by_field_name(
        self, name: Literal["body"], /
    ) -> list[TemplateDirective | TemplateInterpolation | TemplateLiteral]: ...
    @override
    def child_by_field_name(
        self, name: Literal["heredoc_marker"], /
    ) -> HeredocStart: ...
    @property
    @override
    def named_children(self) -> list[HeredocIdentifier]: ...
    @property
    @override
    def children(self) -> list[HeredocIdentifier]: ...

class Index(NamedNode[Literal["index"]]):
    ...
    @override
    @overload
    def child_by_field_name(
        self, name: Literal["index"], /
    ) -> LegacyIndex | NewIndex: ...
    @overload
    def child_by_field_name(self, name: Literal["object"], /) -> ExprTerm: ...

class LegacyIndex(NamedNode[Literal["legacy_index"]]): ...

class NewIndex(NamedNode[Literal["new_index"]]):
    ...

    @property
    @override
    def named_children(self) -> list[Expression]: ...
    @property
    @override
    def children(self) -> list[Expression]: ...

class NumericLit(NamedNode[Literal["numeric_lit"]]): ...

class Object(NamedNode[Literal["object"]]):
    ...
    @override
    def children_by_field_name(
        self, name: Literal["elements"], /
    ) -> list[ObjectElem]: ...
    @property
    @override
    def named_children(self) -> list[ObjectEnd | ObjectStart]: ...
    @property
    @override
    def children(self) -> list[ObjectEnd | ObjectStart]: ...

class ObjectElem(NamedNode[Literal["object_elem"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["key"], /) -> Expression: ...
    @overload
    def child_by_field_name(self, name: Literal["val"], /) -> Expression: ...

class ObjectEnd(NamedNode[Literal["object_end"]]): ...
class ObjectStart(NamedNode[Literal["object_start"]]): ...

class ParenthesizedExpression(NamedNode[Literal["parenthesized_expression"]]):
    ...

    @property
    @override
    def named_children(self) -> list[Expression]: ...
    @property
    @override
    def children(self) -> list[Expression]: ...

class QuotedTemplate(NamedNode[Literal["quoted_template"]]):
    ...
    @override
    def children_by_field_name(
        self, name: Literal["body"], /
    ) -> list[TemplateDirective | TemplateInterpolation | TemplateLiteral]: ...
    @property
    @override
    def named_children(self) -> list[QuotedTemplateEnd | QuotedTemplateStart]: ...
    @property
    @override
    def children(self) -> list[QuotedTemplateEnd | QuotedTemplateStart]: ...

class StringLit(NamedNode[Literal["string_lit"]]):
    ...
    @override
    def child_by_field_name(
        self, name: Literal["body"], /
    ) -> TemplateLiteral | None: ...
    @property
    @override
    def named_children(self) -> list[QuotedTemplateEnd | QuotedTemplateStart]: ...
    @property
    @override
    def children(self) -> list[QuotedTemplateEnd | QuotedTemplateStart]: ...

class TemplateElseIntro(NamedNode[Literal["template_else_intro"]]):
    ...
    @override
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_end"], /
    ) -> StripMarker | None: ...
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_start"], /
    ) -> StripMarker | None: ...
    @property
    @override
    def named_children(self) -> list[TemplateDirectiveEnd | TemplateDirectiveStart]: ...
    @property
    @override
    def children(self) -> list[TemplateDirectiveEnd | TemplateDirectiveStart]: ...

class TemplateFor(NamedNode[Literal["template_for"]]):
    ...
    @override
    def children_by_field_name(
        self, name: Literal["body"], /
    ) -> list[TemplateDirective | TemplateInterpolation | TemplateLiteral]: ...
    @override
    def child_by_field_name(self, name: Literal["start"], /) -> TemplateForStart: ...
    @property
    @override
    def named_children(self) -> list[TemplateForEnd]: ...
    @property
    @override
    def children(self) -> list[TemplateForEnd]: ...

class TemplateForEnd(NamedNode[Literal["template_for_end"]]):
    ...
    @override
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_end"], /
    ) -> StripMarker | None: ...
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_start"], /
    ) -> StripMarker | None: ...
    @property
    @override
    def named_children(self) -> list[TemplateDirectiveEnd | TemplateDirectiveStart]: ...
    @property
    @override
    def children(self) -> list[TemplateDirectiveEnd | TemplateDirectiveStart]: ...

class TemplateForStart(NamedNode[Literal["template_for_start"]]):
    ...
    @override
    def children_by_field_name(self, name: Literal["left"], /) -> list[Identifier]: ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["right"], /) -> Expression: ...
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_end"], /
    ) -> StripMarker | None: ...
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_start"], /
    ) -> StripMarker | None: ...
    @property
    @override
    def named_children(self) -> list[TemplateDirectiveEnd | TemplateDirectiveStart]: ...
    @property
    @override
    def children(self) -> list[TemplateDirectiveEnd | TemplateDirectiveStart]: ...

class TemplateIf(NamedNode[Literal["template_if"]]):
    ...
    @override
    @overload
    def children_by_field_name(
        self, name: Literal["else_body"], /
    ) -> list[TemplateDirective | TemplateInterpolation | TemplateLiteral]: ...
    @override
    @overload
    def child_by_field_name(
        self, name: Literal["else_intro"], /
    ) -> TemplateElseIntro | None: ...
    @overload
    def children_by_field_name(
        self, name: Literal["if_body"], /
    ) -> list[TemplateDirective | TemplateInterpolation | TemplateLiteral]: ...
    @overload
    def child_by_field_name(self, name: Literal["if_intro"], /) -> TemplateIfIntro: ...
    @property
    @override
    def named_children(self) -> list[TemplateIfEnd]: ...
    @property
    @override
    def children(self) -> list[TemplateIfEnd]: ...

class TemplateIfEnd(NamedNode[Literal["template_if_end"]]):
    ...
    @override
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_end"], /
    ) -> StripMarker | None: ...
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_start"], /
    ) -> StripMarker | None: ...
    @property
    @override
    def named_children(self) -> list[TemplateDirectiveEnd | TemplateDirectiveStart]: ...
    @property
    @override
    def children(self) -> list[TemplateDirectiveEnd | TemplateDirectiveStart]: ...

class TemplateIfIntro(NamedNode[Literal["template_if_intro"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["condition"], /) -> Expression: ...
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_end"], /
    ) -> StripMarker | None: ...
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_start"], /
    ) -> StripMarker | None: ...
    @property
    @override
    def named_children(self) -> list[TemplateDirectiveEnd | TemplateDirectiveStart]: ...
    @property
    @override
    def children(self) -> list[TemplateDirectiveEnd | TemplateDirectiveStart]: ...

class TemplateInterpolation(NamedNode[Literal["template_interpolation"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["body"], /) -> Expression: ...
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_end"], /
    ) -> StripMarker | None: ...
    @overload
    def child_by_field_name(
        self, name: Literal["strip_marker_start"], /
    ) -> StripMarker | None: ...
    @property
    @override
    def named_children(
        self,
    ) -> list[TemplateInterpolationEnd | TemplateInterpolationStart]: ...
    @property
    @override
    def children(
        self,
    ) -> list[TemplateInterpolationEnd | TemplateInterpolationStart]: ...

class TemplateLiteral(NamedNode[Literal["template_literal"]]): ...

class Tuple(NamedNode[Literal["tuple"]]):
    ...
    @override
    def children_by_field_name(
        self, name: Literal["elements"], /
    ) -> list[Expression]: ...
    @property
    @override
    def named_children(self) -> list[TupleEnd | TupleStart]: ...
    @property
    @override
    def children(self) -> list[TupleEnd | TupleStart]: ...

class TupleEnd(NamedNode[Literal["tuple_end"]]): ...
class TupleStart(NamedNode[Literal["tuple_start"]]): ...

class UnaryOperation(NamedNode[Literal["unary_operation"]]):
    ...
    @override
    @overload
    def child_by_field_name(self, name: Literal["operand"], /) -> ExprTerm: ...
    @overload
    def child_by_field_name(
        self, name: Literal["operator"], /
    ) -> UnnamedNode[Literal["!"]] | UnnamedNode[Literal["-"]]: ...

class Comment(NamedNode[Literal["comment"]]): ...
class Ellipsis(NamedNode[Literal["ellipsis"]]): ...
class ForInitializerSingle(NamedNode[Literal["for_initializer_single"]]): ...
class HeredocIdentifier(NamedNode[Literal["heredoc_identifier"]]): ...
class Identifier(NamedNode[Literal["identifier"]]): ...
class NullLit(NamedNode[Literal["null_lit"]]): ...
class QuotedTemplateEnd(NamedNode[Literal["quoted_template_end"]]): ...
class QuotedTemplateStart(NamedNode[Literal["quoted_template_start"]]): ...
class StripMarker(NamedNode[Literal["strip_marker"]]): ...
class TemplateDirectiveEnd(NamedNode[Literal["template_directive_end"]]): ...
class TemplateDirectiveStart(NamedNode[Literal["template_directive_start"]]): ...
class TemplateInterpolationEnd(NamedNode[Literal["template_interpolation_end"]]): ...
class TemplateInterpolationStart(
    NamedNode[Literal["template_interpolation_start"]]
): ...

type CollectionValue = "Tuple" | "Object"
type ExprTerm = (
    "FunctionCall"
    | "ParenthesizedExpression"
    | "Identifier"
    | "UnaryOperation"
    | "Index"
    | "ForExpr"
    | "LiteralValue"
    | "GetAttr"
    | "TemplateExpr"
    | "CollectionValue"
    | "Splat"
    | "BinaryOperation"
)
type Expression = "Conditional" | "ExprTerm"
type ForExpr = "ForObjectExpr" | "ForTupleExpr"
type LiteralValue = "NullLit" | "NumericLit" | "StringLit" | "BoolLit"
type Splat = "FullSplat" | "AttrSplat"
type TemplateDirective = "TemplateIf" | "TemplateFor"
type TemplateExpr = "HeredocTemplate" | "QuotedTemplate"
type HclNode = (
    CollectionValue
    | ExprTerm
    | Expression
    | ForExpr
    | LiteralValue
    | Splat
    | TemplateDirective
    | TemplateExpr
    | AttrSplat
    | Attribute
    | BinaryOperation
    | Block
    | BlockEnd
    | BlockStart
    | Body
    | BoolLit
    | Conditional
    | ConfigFile
    | ForInitializerPair
    | ForIntro
    | ForObjectExpr
    | ForTupleExpr
    | FullSplat
    | FunctionCall
    | GetAttr
    | HeredocStart
    | HeredocTemplate
    | Index
    | LegacyIndex
    | NewIndex
    | NumericLit
    | Object
    | ObjectElem
    | ObjectEnd
    | ObjectStart
    | ParenthesizedExpression
    | QuotedTemplate
    | StringLit
    | TemplateElseIntro
    | TemplateFor
    | TemplateForEnd
    | TemplateForStart
    | TemplateIf
    | TemplateIfEnd
    | TemplateIfIntro
    | TemplateInterpolation
    | TemplateLiteral
    | Tuple
    | TupleEnd
    | TupleStart
    | UnaryOperation
    | UnnamedNode[Literal["!"]]
    | UnnamedNode[Literal["!="]]
    | UnnamedNode[Literal["%"]]
    | UnnamedNode[Literal["&&"]]
    | UnnamedNode[Literal["("]]
    | UnnamedNode[Literal[")"]]
    | UnnamedNode[Literal["*"]]
    | UnnamedNode[Literal["+"]]
    | UnnamedNode[Literal[","]]
    | UnnamedNode[Literal["-"]]
    | UnnamedNode[Literal["."]]
    | UnnamedNode[Literal[".*"]]
    | UnnamedNode[Literal["/"]]
    | UnnamedNode[Literal[":"]]
    | UnnamedNode[Literal["<"]]
    | UnnamedNode[Literal["<<"]]
    | UnnamedNode[Literal["<<-"]]
    | UnnamedNode[Literal["<="]]
    | UnnamedNode[Literal["="]]
    | UnnamedNode[Literal["=="]]
    | UnnamedNode[Literal["=>"]]
    | UnnamedNode[Literal[">"]]
    | UnnamedNode[Literal[">="]]
    | UnnamedNode[Literal["?"]]
    | UnnamedNode[Literal["["]]
    | UnnamedNode[Literal["[*]"]]
    | UnnamedNode[Literal["]"]]
    | Comment
    | Ellipsis
    | UnnamedNode[Literal["else"]]
    | UnnamedNode[Literal["endfor"]]
    | UnnamedNode[Literal["endif"]]
    | UnnamedNode[Literal["false"]]
    | UnnamedNode[Literal["for"]]
    | ForInitializerSingle
    | HeredocIdentifier
    | Identifier
    | UnnamedNode[Literal["if"]]
    | UnnamedNode[Literal["in"]]
    | NullLit
    | QuotedTemplateEnd
    | QuotedTemplateStart
    | StripMarker
    | TemplateDirectiveEnd
    | TemplateDirectiveStart
    | TemplateInterpolationEnd
    | TemplateInterpolationStart
    | UnnamedNode[Literal["true"]]
    | UnnamedNode[Literal["{"]]
    | UnnamedNode[Literal["||"]]
    | UnnamedNode[Literal["}"]]
)
